// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ej8DxXtdPxeeRR7ubTd3E-Q96MSCaHw',
    appId: '1:644064769095:web:10f62519a2b6a9fecded62',
    messagingSenderId: '644064769095',
    projectId: 'leem-a488e',
    authDomain: 'leem-a488e.firebaseapp.com',
    storageBucket: 'leem-a488e.firebasestorage.app',
    measurementId: 'G-H1TTQN8TD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe397tMf5JMGXMzP_4p_s3TOpUHc0jrKY',
    appId: '1:644064769095:android:3727c9e9c74d25f9cded62',
    messagingSenderId: '644064769095',
    projectId: 'leem-a488e',
    storageBucket: 'leem-a488e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQaKf7T1Y4H9D9zM3i6TqUDh7FWksb64Y',
    appId: '1:644064769095:ios:44e783508da7f11dcded62',
    messagingSenderId: '644064769095',
    projectId: 'leem-a488e',
    storageBucket: 'leem-a488e.firebasestorage.app',
    iosClientId: '644064769095-trbumh2ii7sniisjlmtoilopmdqlatnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfumeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQaKf7T1Y4H9D9zM3i6TqUDh7FWksb64Y',
    appId: '1:644064769095:ios:44e783508da7f11dcded62',
    messagingSenderId: '644064769095',
    projectId: 'leem-a488e',
    storageBucket: 'leem-a488e.firebasestorage.app',
    iosClientId: '644064769095-trbumh2ii7sniisjlmtoilopmdqlatnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfumeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8ej8DxXtdPxeeRR7ubTd3E-Q96MSCaHw',
    appId: '1:644064769095:web:f74d3cf4e385aa96cded62',
    messagingSenderId: '644064769095',
    projectId: 'leem-a488e',
    authDomain: 'leem-a488e.firebaseapp.com',
    storageBucket: 'leem-a488e.firebasestorage.app',
    measurementId: 'G-CWBS1DXLL6',
  );

}